services:
  # Backend Node.js Service
  - type: web
    name: baymax-backend
    env: node
    region: oregon
    plan: free
    repo: https://github.com/Veerasuryahub/baymax-hcc
    branch: main
    rootDir: backend
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      # - key: MONGO_URI
      #   value: your_real_mongo_uri_here 

  # Frontend React Service
  - type: web
    name: baymax-frontend
    env: static
    plan: free
    repo: https://github.com/Veerasuryahub/baymax-hcc
    branch: main
    rootDir: front
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: baymax-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_BOT_URL
        fromService:
          type: web
          name: baymax-bot
          envVarKey: RENDER_EXTERNAL_URL
      
  # Python Bot Service
  - type: web
    name: baymax-bot
    env: python
    region: oregon
    plan: free
    repo: https://github.com/Veerasuryahub/baymax-hcc
    branch: main
    rootDir: Bot
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
