services:
  # Backend Node.js Service
  - type: web
    name: baymax-backend
    env: node
    region: oregon
    plan: free
    repo: https://github.com/Veerasuryahub/baymax-hcc
    branch: main
    rootDir: backend
    buildCommand: rm -rf node_modules package-lock.json && npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://veera:veerasurya@cluster0.cxhtovi.mongodb.net/baymax?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: bXm9$kR2!wZ7@pL4qHs6&vF1jY8*nT3cG0dA5eU
      - key: FRONTEND_URL
        fromService:
          type: web
          name: baymax-frontend
          envVarKey: RENDER_EXTERNAL_URL

  # Frontend React Service
  - type: web
    name: baymax-frontend
    env: static
    repo: https://github.com/Veerasuryahub/baymax-hcc
    branch: main
    rootDir: front
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: baymax-backend
          envVarKey: RENDER_EXTERNAL_URL
      - key: VITE_BOT_URL
        fromService:
          type: web
          name: baymax-bot
          envVarKey: RENDER_EXTERNAL_URL
      
  # Python Bot Service
  - type: web
    name: baymax-bot
    env: python
    region: oregon
    plan: free
    repo: https://github.com/Veerasuryahub/baymax-hcc
    branch: main
    rootDir: Bot
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: baymax-frontend
          envVarKey: RENDER_EXTERNAL_URL
